/** ISO 3166-1 alpha-2 code + international calling code for phone number entry. Not exhaustive — covers the countries users are overwhelmingly likely to need. */
export const COUNTRY_CODES = [
  { name: 'United States', iso2: 'US', dialCode: '+1' },
  { name: 'Canada', iso2: 'CA', dialCode: '+1' },
  { name: 'United Kingdom', iso2: 'GB', dialCode: '+44' },
  { name: 'Ireland', iso2: 'IE', dialCode: '+353' },
  { name: 'Nigeria', iso2: 'NG', dialCode: '+234' },
  { name: 'Ghana', iso2: 'GH', dialCode: '+233' },
  { name: 'Kenya', iso2: 'KE', dialCode: '+254' },
  { name: 'South Africa', iso2: 'ZA', dialCode: '+27' },
  { name: 'Egypt', iso2: 'EG', dialCode: '+20' },
  { name: 'Ethiopia', iso2: 'ET', dialCode: '+251' },
  { name: 'Morocco', iso2: 'MA', dialCode: '+212' },
  { name: 'Germany', iso2: 'DE', dialCode: '+49' },
  { name: 'France', iso2: 'FR', dialCode: '+33' },
  { name: 'Spain', iso2: 'ES', dialCode: '+34' },
  { name: 'Portugal', iso2: 'PT', dialCode: '+351' },
  { name: 'Italy', iso2: 'IT', dialCode: '+39' },
  { name: 'Netherlands', iso2: 'NL', dialCode: '+31' },
  { name: 'Belgium', iso2: 'BE', dialCode: '+32' },
  { name: 'Switzerland', iso2: 'CH', dialCode: '+41' },
  { name: 'Austria', iso2: 'AT', dialCode: '+43' },
  { name: 'Sweden', iso2: 'SE', dialCode: '+46' },
  { name: 'Norway', iso2: 'NO', dialCode: '+47' },
  { name: 'Denmark', iso2: 'DK', dialCode: '+45' },
  { name: 'Finland', iso2: 'FI', dialCode: '+358' },
  { name: 'Poland', iso2: 'PL', dialCode: '+48' },
  { name: 'Czech Republic', iso2: 'CZ', dialCode: '+420' },
  { name: 'Greece', iso2: 'GR', dialCode: '+30' },
  { name: 'Turkey', iso2: 'TR', dialCode: '+90' },
  { name: 'Russia', iso2: 'RU', dialCode: '+7' },
  { name: 'Ukraine', iso2: 'UA', dialCode: '+380' },
  { name: 'India', iso2: 'IN', dialCode: '+91' },
  { name: 'Pakistan', iso2: 'PK', dialCode: '+92' },
  { name: 'Bangladesh', iso2: 'BD', dialCode: '+880' },
  { name: 'China', iso2: 'CN', dialCode: '+86' },
  { name: 'Japan', iso2: 'JP', dialCode: '+81' },
  { name: 'South Korea', iso2: 'KR', dialCode: '+82' },
  { name: 'Singapore', iso2: 'SG', dialCode: '+65' },
  { name: 'Malaysia', iso2: 'MY', dialCode: '+60' },
  { name: 'Indonesia', iso2: 'ID', dialCode: '+62' },
  { name: 'Philippines', iso2: 'PH', dialCode: '+63' },
  { name: 'Vietnam', iso2: 'VN', dialCode: '+84' },
  { name: 'Thailand', iso2: 'TH', dialCode: '+66' },
  { name: 'United Arab Emirates', iso2: 'AE', dialCode: '+971' },
  { name: 'Saudi Arabia', iso2: 'SA', dialCode: '+966' },
  { name: 'Qatar', iso2: 'QA', dialCode: '+974' },
  { name: 'Israel', iso2: 'IL', dialCode: '+972' },
  { name: 'Australia', iso2: 'AU', dialCode: '+61' },
  { name: 'New Zealand', iso2: 'NZ', dialCode: '+64' },
  { name: 'Brazil', iso2: 'BR', dialCode: '+55' },
  { name: 'Mexico', iso2: 'MX', dialCode: '+52' },
  { name: 'Argentina', iso2: 'AR', dialCode: '+54' },
  { name: 'Chile', iso2: 'CL', dialCode: '+56' },
  { name: 'Colombia', iso2: 'CO', dialCode: '+57' },
  { name: 'Peru', iso2: 'PE', dialCode: '+51' },
]

/** Renders an ISO 3166-1 alpha-2 code as its flag emoji via Unicode regional indicator symbols — no image assets needed. */
export function flagEmoji(iso2) {
  return iso2
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)))
}
