export const analysisHistorySample = [
  {
    id: 'hist-1',
    resumeFilename: 'Jordan_Cole_Resume.pdf',
    jobTitle: 'Senior Frontend Engineer',
    overallScore: 82,
    analyzedAt: '2026-07-20T14:32:00Z',
    skillMatch: { skill_score: 88, matched_skills: ['react', 'typescript', 'css', 'graphql'], missing_skills: ['webgl'] },
    experienceMatch: { experience_score: 100, required_years: 4, candidate_years_found: 6 },
    qualificationMatch: { qualification_score: 100, matched_qualifications: ['bachelor'] },
  },
  {
    id: 'hist-2',
    resumeFilename: 'Jordan_Cole_Resume.pdf',
    jobTitle: 'Backend Engineer (Python)',
    overallScore: 61,
    analyzedAt: '2026-07-18T09:05:00Z',
    skillMatch: { skill_score: 55, matched_skills: ['python', 'postgresql'], missing_skills: ['django', 'kubernetes', 'redis'] },
    experienceMatch: { experience_score: 70, required_years: 5, candidate_years_found: 6 },
    qualificationMatch: { qualification_score: 100, matched_qualifications: ['bachelor'] },
  },
  {
    id: 'hist-3',
    resumeFilename: 'Jordan_Cole_Resume_v2.docx',
    jobTitle: 'Full Stack Developer',
    overallScore: 74,
    analyzedAt: '2026-07-10T17:48:00Z',
    skillMatch: { skill_score: 78, matched_skills: ['react', 'node', 'sql'], missing_skills: ['aws'] },
    experienceMatch: { experience_score: 100, required_years: 3, candidate_years_found: 6 },
    qualificationMatch: { qualification_score: 0, note: 'No specific qualification required' },
  },
  {
    id: 'hist-4',
    resumeFilename: 'Jordan_Cole_Resume_v2.docx',
    jobTitle: 'UI Engineer',
    overallScore: 45,
    analyzedAt: '2026-06-29T11:15:00Z',
    skillMatch: { skill_score: 40, matched_skills: ['css', 'figma'], missing_skills: ['react', 'vue', 'accessibility'] },
    experienceMatch: { experience_score: 30, required_years: 4, candidate_years_found: 0 },
    qualificationMatch: { qualification_score: 100, note: 'No specific qualification required' },
  },
]
